# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messagesPrueba.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messagesPrueba.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14messagesPrueba.proto\"\xc0\x01\n\x13MensajePruebasPySTM\x12\x12\n\ndigitalPin\x18\x01 \x02(\x05\x12\x11\n\tanalogPin\x18\x02 \x02(\x05\x12\x0e\n\x06\x63odigo\x18\x03 \x02(\x05\x12:\n\nnew_values\x18\x04 \x01(\x0e\x32\x1e.MensajePruebasPySTM.NewValues:\x06NUMBER\"6\n\tNewValues\x12\t\n\x05HOUSE\x10\x01\x12\x07\n\x03WEB\x10\x02\x12\n\n\x06NUMBER\x10\x03\x12\t\n\x05VIDEO\x10\x04'
)



_MENSAJEPRUEBASPYSTM_NEWVALUES = _descriptor.EnumDescriptor(
  name='NewValues',
  full_name='MensajePruebasPySTM.NewValues',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HOUSE', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEB', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NUMBER', index=2, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=3, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=163,
  serialized_end=217,
)
_sym_db.RegisterEnumDescriptor(_MENSAJEPRUEBASPYSTM_NEWVALUES)


_MENSAJEPRUEBASPYSTM = _descriptor.Descriptor(
  name='MensajePruebasPySTM',
  full_name='MensajePruebasPySTM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='digitalPin', full_name='MensajePruebasPySTM.digitalPin', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='analogPin', full_name='MensajePruebasPySTM.analogPin', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='codigo', full_name='MensajePruebasPySTM.codigo', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='new_values', full_name='MensajePruebasPySTM.new_values', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MENSAJEPRUEBASPYSTM_NEWVALUES,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=217,
)

_MENSAJEPRUEBASPYSTM.fields_by_name['new_values'].enum_type = _MENSAJEPRUEBASPYSTM_NEWVALUES
_MENSAJEPRUEBASPYSTM_NEWVALUES.containing_type = _MENSAJEPRUEBASPYSTM
DESCRIPTOR.message_types_by_name['MensajePruebasPySTM'] = _MENSAJEPRUEBASPYSTM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MensajePruebasPySTM = _reflection.GeneratedProtocolMessageType('MensajePruebasPySTM', (_message.Message,), {
  'DESCRIPTOR' : _MENSAJEPRUEBASPYSTM,
  '__module__' : 'messagesPrueba_pb2'
  # @@protoc_insertion_point(class_scope:MensajePruebasPySTM)
  })
_sym_db.RegisterMessage(MensajePruebasPySTM)


# @@protoc_insertion_point(module_scope)
