/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_MESSAGESPRUEBA_PB_H_INCLUDED
#define PB_MESSAGESPRUEBA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _MensajePruebasPySTM_NewValues {
    MensajePruebasPySTM_NewValues_HOUSE = 1,
    MensajePruebasPySTM_NewValues_WEB = 2,
    MensajePruebasPySTM_NewValues_NUMBER = 3,
    MensajePruebasPySTM_NewValues_VIDEO = 4
} MensajePruebasPySTM_NewValues;

/* Struct definitions */
typedef struct _MensajePruebasPySTM {
    int32_t digitalPin;
    int32_t analogPin;
    int32_t codigo;
    bool has_new_values;
    MensajePruebasPySTM_NewValues new_values;
} MensajePruebasPySTM;


/* Helper constants for enums */
#define _MensajePruebasPySTM_NewValues_MIN MensajePruebasPySTM_NewValues_HOUSE
#define _MensajePruebasPySTM_NewValues_MAX MensajePruebasPySTM_NewValues_VIDEO
#define _MensajePruebasPySTM_NewValues_ARRAYSIZE ((MensajePruebasPySTM_NewValues)(MensajePruebasPySTM_NewValues_VIDEO+1))


/* Initializer values for message structs */
#define MensajePruebasPySTM_init_default         {0, 0, 0, false, MensajePruebasPySTM_NewValues_NUMBER}
#define MensajePruebasPySTM_init_zero            {0, 0, 0, false, _MensajePruebasPySTM_NewValues_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define MensajePruebasPySTM_digitalPin_tag       1
#define MensajePruebasPySTM_analogPin_tag        2
#define MensajePruebasPySTM_codigo_tag           3
#define MensajePruebasPySTM_new_values_tag       4

/* Struct field encoding specification for nanopb */
#define MensajePruebasPySTM_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, INT32,    digitalPin,        1) \
X(a, STATIC,   REQUIRED, INT32,    analogPin,         2) \
X(a, STATIC,   REQUIRED, INT32,    codigo,            3) \
X(a, STATIC,   OPTIONAL, UENUM,    new_values,        4)
#define MensajePruebasPySTM_CALLBACK NULL
#define MensajePruebasPySTM_DEFAULT (const pb_byte_t*)"\x20\x03\x00"

extern const pb_msgdesc_t MensajePruebasPySTM_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MensajePruebasPySTM_fields &MensajePruebasPySTM_msg

/* Maximum encoded size of messages (where known) */
#define MensajePruebasPySTM_size                 35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
